services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - INFISICAL_CLIENT_ID
      - INFISICAL_CLIENT_SECRET
      - INFISICAL_PROJECT_ID
      - INFISICAL_ENVIRONMENT
      - INFISICAL_SITE_URL
    depends_on:
      - auth-service
      - non-auth-service
    networks:
      - microservices-net

  auth-service:
    build: ./auth-service
    environment:
      - INFISICAL_CLIENT_ID
      - INFISICAL_CLIENT_SECRET
      - INFISICAL_PROJECT_ID
      - INFISICAL_ENVIRONMENT
      - INFISICAL_SITE_URL
    networks:
      - microservices-net

  non-auth-service:
    build: ./non-auth-service
    environment:
      - INFISICAL_CLIENT_ID
      - INFISICAL_CLIENT_SECRET
      - INFISICAL_PROJECT_ID
      - INFISICAL_ENVIRONMENT
      - INFISICAL_SITE_URL
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
