services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4001
      - NON_AUTH_SERVICE_URL=http://non-auth-service:4002
    depends_on:
      - auth-service
      - non-auth-service
    networks:
      - microservices-net

  auth-service:
    build: ./auth-service
    expose:
      - "4001"
    networks:
      - microservices-net

  non-auth-service:
    build: ./non-auth-service
    expose:
      - "4002"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

    


    






